#Exceptions
# To handle issues in software we can use a Try-Except block

def func():
    try: # Try this 
        print(value)
    except: # If try fails run this 
        print("There was a problem")

func()